[build-system]
requires = [
    "setuptools>=68.0.0",
    "wheel>=0.40.0"
]
build-backend = "setuptools.build_meta"

[project]
name = "file-convection"
version = "1.0.0"
requires-python = ">=3.11.7,<3.12"

[tool.poetry.dependencies]
python = "^3.11.7"