services:
  - type: web
    name: bank-statement-converter
    env: python
    buildCommand: |
      # Install system dependencies
      apt-get update && apt-get install -y default-jdk build-essential python3-dev
      # Upgrade pip and install build tools
      python -m pip install --upgrade pip setuptools wheel
      # Install requirements
      pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: FLASK_ENV
        value: "production"
      - key: UPLOAD_DIR
        value: "/tmp/uploads"
      - key: OUTPUT_DIR
        value: "/tmp/outputs"