services:
  - type: web
    name: file-convection
    env: python
    # The python version is set in the Render Dashboard
    # PYTHON_VERSION = 3.11.7
    buildCommand: "apt-get update && apt-get install -y default-jdk && mkdir -p logs && pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: JAVA_HOME
        value: /usr/lib/jvm/default-java
    healthCheckPath: /health
    autoDeploy: true