services:
  - type: web
    name: file-convection
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: PORT
        value: 8000
      - key: FLASK_ENV
        value: production
    healthCheckPath: /health