services:
  - type: web
    name: file-convection
    env: python
    buildCommand: pip install poetry && poetry install
    startCommand: poetry run python wsgi.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.7
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
      - key: THREADS
        value: 4
      - key: FLASK_ENV
        value: production
    autoDeploy: true