services:
  - type: web
    name: hnf-pdf-converter
    env: python
    buildCommand: |
      apt-get update && apt-get install -y default-jdk  # ← This installs Java
      export JAVA_HOME=/usr/lib/jvm/default-java
      export PATH=$PATH:$JAVA_HOME/bin
      pip install --only-binary=all -r requirements.txt  # ← This uses your requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 300
    plan: free
    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/default-java
      - key: PATH
        value: /usr/lib/jvm/default-java/bin:$PATH
    autoDeploy: true
