services:
  - type: web
    name: file-convection
    env: python
    # The python version is now set in the Render Dashboard Environment Variables
    # PYTHON_VERSION = 3.11.7
    buildCommand: "pip install -r requirements.txt && mkdir -p logs"
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: JAVA_HOME
        value: /usr/lib/jvm/default-java
    healthCheckPath: /health
    autoDeploy: true